package application;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

import javafx.scene.control.Slider;

import javafx.scene.control.ComboBox;

import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;

import javafx.scene.control.CheckBox;

public class SettingsController {
	@FXML
	private ComboBox cardBackSelector;
	@FXML
	private ComboBox drawTypeSelector;
	@FXML
	private Slider masterVolumeSlider;
	@FXML
	private Slider musicVolumeSlider;
	@FXML
	private Slider effectsVolumeSlider;
	@FXML
	private CheckBox undoSelection;
	@FXML
	private CheckBox solveableSelection;
	@FXML
	private CheckBox showTimeSelection;
	@FXML
	private ImageView cardBackPreview;

	// Event Listener on ComboBox[#cardBackSelector].onAction
	@FXML
	public void updateCardBack(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#drawTypeSelector].onAction
	@FXML
	public void updateDrawType(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Slider[#masterVolumeSlider].onDragDetected
	@FXML
	public void masterVolumeDragged(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Slider[#musicVolumeSlider].onDragDetected
	@FXML
	public void musicVolumeDragged(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Slider[#effectsVolumeSlider].onDragDetected
	@FXML
	public void effectsVolumeDragged(MouseEvent event) {
		// TODO Autogenerated
	}
}
